# Generated by Django 4.0.4 on 2022-05-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_trade_coment_auctions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='auction_exhibitor',
        ),
        migrations.AddField(
            model_name='auctions',
            name='auction_title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
