# Generated by Django 4.0.4 on 2022-05-31 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_auctions_auction_exhibitor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='auction_exhibitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
