# Generated by Django 4.0.4 on 2022-06-03 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctions_auction_exhibitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='auction_categoli',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='auction_daytime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='auction_exhibitor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='auction_limittime',
            field=models.CharField(choices=[('1', '3Hours'), ('2', '12Hours'), ('3', '24Hours'), ('4', '3days')], max_length=1),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='auction_picture',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='auction_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='coment',
            name='coment_daytime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_daitime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
