# Generated by Django 4.0.4 on 2022-06-03 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctions_auction_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='auction_limittime',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='auction_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
