# Generated by Django 4.0.4 on 2022-06-03 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auctions_auction_daytime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='auction_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='auction_limittime',
            field=models.CharField(choices=[('1', '3Hours'), ('2', '12Hours'), ('3', '24Hours'), ('4', '3days')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='auction_price',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
