# Generated by Django 4.0.4 on 2022-06-07 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auctions_auction_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='auction_daytime',
        ),
        migrations.AddField(
            model_name='auctions',
            name='auction_validity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_auction_ID',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_validity',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='coment',
            name='coment_user',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_bidder',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
