# Generated by Django 4.0.4 on 2022-06-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_auctions_auction_daytime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='trade_daitime',
            new_name='trade_daytime',
        ),
        migrations.AddField(
            model_name='auctions',
            name='auction_daytime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
