# Generated by Django 4.0.4 on 2022-06-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_rename_trade_daitime_trade_trade_daytime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='auction_daytime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='auction_picture',
            field=models.ImageField(blank=True, default='image/NoImage.jpeg', null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='coment',
            name='coment_daytime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_daytime',
            field=models.DateTimeField(null=True),
        ),
    ]
