# Generated by Django 4.0.4 on 2022-06-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_auctions_auction_daytime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='coment_auction_ID',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
