# Generated by Django 4.0.4 on 2022-06-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_coment_coment_auction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='coment_auction_ID',
            field=models.IntegerField(null=True),
        ),
    ]
